[tool.poetry]
name = "syntarch"
version = "0.1.0"
description = ""
authors = ["Chatyusha <hirounicat76@gmail.com>"]
readme = "README.md"
exclude = ["build/"]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
