class TokenTypes():
    TYPE_HEAD = "head"
    TYPE_CODE_BLOCK = "codeb_lock"
    TYPE_QUOTE_BLOCK = "quote_block"
    TYPE_TABLE = "table"
    TYPE_PARAGRAPH = "paragraph"
    TYPE_DISPLAY_MATH = "display_math"
    TYPE_DOT_LIST = "dot_list"
    TYPE_PLAINE = "plaine"
    TYPE_EMPHASIS = "emphasis"
    TYPE_ITALIC = "italic"
    TYPE_INLINE = "inline"
    TYPE_INLINE_MATH = "inline_math"
    TYPE_NEW_LINE = "new_line"
    TYPE_PHRASE = "phrase"

    TABLE_POSITION_LEFT = "table_left"
    TABLE_POSITION_CENTER = "table_center"
    TABLE_POSITION_RIGHT = "table_right"